#!/bin/sh
pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V
# (I put in the xrandr setup for my monitor setup so change this to fit yours if needed)
#xrandr --output eDP-1 --mode 1366x768 --right-of HDMI-1
#xrandr --output HDMI-1 --mode 1920x1080 --left-of eDP-1

unclutter -idle 4 &
xsetroot -cursor_name left_ptr
xinput --set-prop 10 "libinput Accel Profile Enabled" 0, 1

feh --bg-fill /home/xzrc07/Images/purple.jpg

bspc config border_width 1
bspc config window_gap 2
bspc config split_ratio 0.50
bspc config borderless_monicle true
bspc config gapless_monicle true
bspc config focus_follows_pointer true

# -----+ autostart +----- #
picom &
nm-applet &
polybar &
# ----------------------- #
bspc rule -a "Feh" state=floating
bspc rule -a "Mpv" state=floating
bspc rule -a "Gimp" state=floating
bspc rule -a "Thunar" state=floating
bspc rule -a "pavucontrol" state=floating
bspc rule -a "lxappearance" state=floating
